language: node_js
node_js:
  - 4.3.1
services:
  - mongodb
script:
  - npm test
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: oy40SRfB1bYXqXgNbOxPRSr6MGkJJv6tzLsRWiF5e8ujUcwicn7OHlqJGig4H26E5ResrlVqfyDC7jxLhRXZJZIOnzgHc41sFDbQWOMx4J4n+m+Q4jC1ZGhETgc+zsyGZnJ96rYkPJUR96VR656Kd6IdTwIWYdGpcz1+8S+F/ivDXPulojroNul2CPxa3sHVBQ1xAvmND3uBc8iNWWWonVOkRPWCij8+PH3rxCLTAw0gmLiUnj+k3Y0QhjL6tUWSznyo/6HXzRTvMTVBFNu7IeF1+Afu5ZmQF4ZNUIEoNbsX1hh5KsketFkXo2udySghteVNOxTZs5BmpThik0XsvwF7V4QE1U8zHfO1mApICE4WAydrSB3GilQO4rnspLweVdBEbFplj/eztyjuXBbFd1jVc4taT8XfUfntAzQie2zDHe6/m5F6LC8A2KDX1DfW++s7QuObUxP7WBuKXHvVyz0CgofmG9BO0cC6r3zPPzZkzSE+50G8gtjQTU92OdVw9q0li+TB9QO4Ou2OOSOjEgqsEzijsoG7mbvvp/o5SKkc+ZTPqzpyM6Q8JxDglazGmOmCoGsXIzJLt0UDvOXqTG7Df4lIagKZwA/yZpD6O/gxUhQmfKqKOco8cMXmwZjqTNuGdEGTjqFoSzLXJuCqVIzPBTENFmx7twtPlhOVtJU=
